# Generated by Django 4.2.2 on 2023-12-26 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('class_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.classspacemodel')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.service')),
            ],
        ),
    ]
