# Generated by Django 4.2.2 on 2023-12-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_remove_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tickets',
            field=models.IntegerField(default=1),
        ),
    ]
