# Generated by Django 4.2.9 on 2024-01-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0004_reservation_tickets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="picture",
            field=models.ImageField(upload_to="pictures/"),
        ),
    ]
