# Generated by Django 4.2.9 on 2024-02-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_service_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='classspacemodel',
            name='timezone',
            field=models.CharField(default='UTC', max_length=30),
        ),
    ]
