# Generated by Django 4.2.9 on 2024-02-08 19:42

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_invoice_id_alter_payment_payment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default=payment.models.generate_unique_invoice_id, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_name',
            field=models.CharField(max_length=50),
        ),
    ]
