# Generated by Django 4.2.9 on 2024-02-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_invoice_id_alter_payment_payment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
